### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by VivekUchiha** [VivekUchiha/scrum-master-bot#5]
- [x] Format strings in all places - Print each name on a new line in attendance, Proper spacing between updates.
- [x] Notify Current members if scrum master enters !remind_scrum [time]. Assigned: @TejusR 
- [x] Send list of Absent members after scrum. Assigned: @shambu2k 
- [x] Add CTFtime reminders using clist API. @TejusR  
- [ ] Allow members to specify reason for not attending scrum. Send this to scrum master when scrum starts. Assigned: @TejusR 
- [ ] Add Mongo models for scrum, updates, attendance.
- [x] Send all notice messages(attendance, MOM) on a separate notices channel. Notices channel will be set when scrum_master/admin sends !set_notices_channel in the notices channel.
